[package]
name = "dummy-cruncy-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"
bytes = "1.0"
